CREATE TABLE raw_materials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    stock_quantity DECIMAL(10, 2) NOT NULL
);
ALTER TABLE raw_materials ADD CONSTRAINT uk_raw_materials_name UNIQUE (name);

